[custom]
; Openclash 订阅转换模板 - 静态住宅全局代理版

enable_rule_generator=true
overwrite_original_rules=true
loglevel = Warning
generate_info = true

; 节点清洗：保留你需要的静态住宅节点，剔除多余信息
exclude_remarks=(?i)(?:流量|套餐|到期|剩余|重置|官网|网站|域名|地址|机场|入口|节点|注意|维护|失联|公告|通知|电报|群|频道|说明|最新|客服|工单|订阅|更新|重新|失败|超时|正在|Expire|Traffic|Reset|Remaining|Official|Website|Telegram|TG|QQ)

; --- 局域网与基础直连 (必须保留以访问路由器后台) ---
ruleset=DIRECT,[]GEOSITE,private
ruleset=DIRECT,[]GEOIP,private,no-resolve
ruleset=🔗 住宅中转,clash-classic:https://raw.githubusercontent.com/heimian0722-hash/clashrule/main/StaticResidential.yaml,86400

ruleset=🚀 手动选择,[]GEOSITE,cn
ruleset=🚀 手动选择,[]GEOIP,cn,no-resolve

ruleset=🐟 漏网之鱼,[]FINAL


custom_proxy_group=🚀 手动选择`select`[]🇺🇸 US`[]🇭🇰 HK`[]🇸🇬 SG`[]DIRECT`.*
custom_proxy_group=🔗 住宅中转`select`[]🇺🇸 US`[]🇭🇰 HK`[]🇸🇬 SG
custom_proxy_group=🐟 漏网之鱼`select`[]🗽 纽约住宅出口`[]🚀 手动选择

custom_proxy_group=🇺🇸 US`select`(?i)(🇺🇸|美国|\\bUS\\b|united states|los angeles|san jose|seattle|new york)
custom_proxy_group=🇭🇰 HK`select`(?i)(🇭🇰|香港|\\bHK\\b|hongkong)
custom_proxy_group=🇸🇬 SG`select`(?i)(🇸🇬|新加坡|\\bSG\\b|singapore)
